
version: '3'
services:
  bot:
    build: .
    container_name: telegram_bot
    env_file: .env
    volumes:
      - ./chat.db:/app/chat.db
    expose:
      - "8443"
    restart: always

  web:
    build: .
    container_name: bot_web
    env_file: .env
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: bot_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/bot_logger.conf:/etc/nginx/conf.d/default.conf
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/letsencrypt:/var/www/certbot
    depends_on:
      - bot
      - web
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/letsencrypt:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email your-email@example.com --agree-tos --no-eff-email
      -d checker.gift"
